### ISSUE TITLE
Comentarios

### ISSUE THREAD

**Issue by chanomon** [TJamara/Proyect-Modelado#1]
Creo que ya tienen un buen trabajo pero todavía pueden mejorarlo:

- [x] Para que tenga mejor presentación, a sección "Fuente de datos" debería ir antes de la sección de "pruebas".
- [x] Otra cosa muy importante es que su gráfica de error está diciendo que el modelo diverge con respecto a las efemérides conforme pasa el tiempo,  De cierta manera esto quiere decir que el modelo no está convergiendo correctamente por alguna razón. Podría ser por el código mismo, por las condiciones iniciales, por el dt que están usando, intenten descubrir porqué está pasando esto.
- [x] Respecto a lo anterior, en vez de esa gráfica que pusieron, tomen la distancia que diverge y divídanla entre la distancia promedio de la luna Mimas a Saturno lo que les dará un error relativo, es decir, hagan una gráfica de **e/dp vs días** donde **e** es _error en metros_ y **dp** es la _distancia promedio de Mimas a Saturno_. Esta información les dirá cual es la proporción del error con respecto a la distancia de la órbita de Mimas y les permitirá saber si su error es importante.
Si no lo han hecho, les recomiendo que despues de una ejecución de su modelo guarden los datos de Mimas, así ya no tendrán que volver a ejecutar el modelo para hacer este análisis de datos que les pido.
 - [x] En la preba 3 dicen que están graficando menos puntos, por favor indiquen en qué proporción
- [x] En concluciones también deben discutir si alcanzaron  los objetivos que se propusieron inicialmente, me parece que solo están comentando uno de los objetivos planteados.
- [x] En concluciones mencionan "por eso la importancia de elegír el dt óptimo para reducir las operaciones en órdenes de magnitud" no veo que en el trabajo mencionen cómo escogieron el dt para sus pruebas y si encontraron el dt óptimo.

**Comment by JavoJavo** [comment]
Estuvimos probando un montón de cosas para ver porqué no convergía Mimas y si en realidad no convergía o habíamos hecho alguna otra cosa mal. Luego se nos ocurrió ver si convergía Iapetus que tiene una órbita mucho más amplia y ese sí convergió, la historia completa está en el reporte...

**Comment by chanomon** [comment]
Vale, solo que el problema persiste, está bien si no descubrieron porqué el modelo diverge (en el caso de la luna de Mimas) decir que no sabén porqué es la mejor opción si no tienen una hipótesis fuerte de porqué ocurre esto.

**Comment by chanomon** [comment]
les puse un último comentario.



Elizandro Huipe Domratcheva
Lic. en Geociencias
Universidad Nacional Autónoma de México

**Comment by JavoJavo** [comment]
Hecho. En concreto no sabemos la razón, pero pusimos una hipótesis que se nos ocurrió
